# Generated by Django 6.0 on 2025-12-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('universities', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemadmin',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='universityuser',
            name='associated_university',
        ),
        migrations.RemoveField(
            model_name='universityuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='user',
            name='associated_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='universities.university'),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['associated_university'], name='users_user_associa_c2305c_idx'),
        ),
        migrations.DeleteModel(
            name='SystemAdmin',
        ),
        migrations.DeleteModel(
            name='UniversityUser',
        ),
    ]
