# Generated by Django 6.0 on 2025-12-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_systemadmin_user_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reputation_score',
        ),
    ]
