# Generated by Django 6.0 on 2025-12-13 18:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email_domain', models.CharField(max_length=100, unique=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('space_type', models.CharField(choices=[('studying', 'Studying'), ('eating', 'Eating'), ('coffee', 'Coffee')], max_length=20)),
                ('current_occupancy', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('has_plugs', models.BooleanField(blank=True, null=True)),
                ('has_wifi', models.BooleanField(blank=True, null=True)),
                ('has_student_discounts', models.BooleanField(blank=True, null=True)),
                ('eating_price_range', models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$')], null=True)),
                ('coffee_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('coffee_price_range', models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$')], null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='universities.space')),
            ],
            options={
                'ordering': ['associated_university', 'space_type', 'name'],
            },
        ),
    ]
