# Generated by Django 6.0 on 2025-12-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='is_active',
            new_name='is_approved',
        ),
    ]
