# Generated by Django 6.0 on 2025-12-08 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['university', 'space_type'], name='universitie_univers_b660d4_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['parent'], name='universitie_parent__3ce8ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('university', 'name', 'location')},
        ),
    ]
